<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Employees Attendance Calendar Verify" tests="3" failures="1" timestamp="20 Nov 2017 07:38:42 GMT" time="140.439" errors="0">
  <testcase name="Login" time="1.2" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC015_EmployeeAttendanceCalender_Verify"/>
  <testcase name="TargetPage" time="121.634" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC015_EmployeeAttendanceCalender_Verify"/>
  <testcase name="VerifyAttendanceApproveOrReject" time="4.628" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC015_EmployeeAttendanceCalender_Verify">
    <failure type="java.lang.AssertionError" message="Attendance not rejected">
      <![CDATA[java.lang.AssertionError: Attendance not rejected
	at Module.ESS.LeaveandAttendance.LeaveApplication.TC015_EmployeeAttendanceCalender_Verify.VerifyAttendanceApproveOrReject(TC015_EmployeeAttendanceCalender_Verify.java:82)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- VerifyAttendanceApproveOrReject -->
</testsuite> <!-- Employees Attendance Calendar Verify -->
