<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify" tests="4" failures="1" timestamp="20 Nov 2017 07:29:00 GMT" time="127.180" errors="1">
  <testcase name="TargetPage" time="86.555" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify"/>
  <testcase name="Login" time="2.283" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify"/>
  <testcase name="VerifyAttendanceApprove" time="16.367" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
    <error type="org.testng.SkipException" message="Not Found Locator : Search Dropdown">
      <![CDATA[org.testng.SkipException: Not Found Locator : Search Dropdown
	at pom.TestBase.BaseClass.selectByVisibleText(BaseClass.java:534)
	at pom.TestBase.CommonMethods.Test_Search_Button(CommonMethods.java:134)
	at pom.ObjectPages.uiActions.AttendanceRegularization.Test_Search_Record(AttendanceRegularization.java:112)
	at Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify.VerifyAttendanceApprove(TC012_AttendanceVerify.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- VerifyAttendanceApprove -->
  <testcase name="VerifyAttendanceReject" time="21.975" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
    <failure type="java.lang.AssertionError" message="Attendance not rejected">
      <![CDATA[java.lang.AssertionError: Attendance not rejected
	at org.testng.Assert.fail(Assert.java:94)
	at Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify.VerifyAttendanceReject(TC012_AttendanceVerify.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VerifyAttendanceReject -->
</testsuite> <!-- Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify -->
