<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.ELC.Probation.TC027_ProbationStatusGenerateReport" tests="4" failures="1" timestamp="30 Oct 2017 08:15:11 GMT" time="255.257" errors="0">
  <testcase name="TargetPage" time="167.925" classname="Module.ELC.Probation.TC027_ProbationStatusGenerateReport"/>
  <testcase name="Login" time="1.954" classname="Module.ELC.Probation.TC027_ProbationStatusGenerateReport"/>
  <testcase name="SearchFunctionality" time="19.095" classname="Module.ELC.Probation.TC027_ProbationStatusGenerateReport"/>
  <testcase name="ProbationGenerateReport" time="66.283" classname="Module.ELC.Probation.TC027_ProbationStatusGenerateReport">
    <failure type="java.lang.AssertionError" message="Expected : [Probation Status] But Found : [Welcome to Onex Software]">
      <![CDATA[java.lang.AssertionError: Expected : [Probation Status] But Found : [Welcome to Onex Software]
	at org.testng.Assert.fail(Assert.java:94)
	at Module.ELC.Probation.TC027_ProbationStatusGenerateReport.ProbationGenerateReport(TC027_ProbationStatusGenerateReport.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- ProbationGenerateReport -->
</testsuite> <!-- Module.ELC.Probation.TC027_ProbationStatusGenerateReport -->
